extends Object

const TYPENAME_NIL := "Null"
const TYPENAME_BOOL := "bool"
const TYPENAME_INT := "int"
const TYPENAME_REAL := "float"
const TYPENAME_STRING := "String"
const TYPENAME_VECTOR2 := "Vector2"
const TYPENAME_RECT2 := "Rect2"
const TYPENAME_VECTOR3 := "Vector3"
const TYPENAME_TRANSFORM2D := "Transform2D"
const TYPENAME_PLANE := "Plane"
const TYPENAME_QUAT := "Quat"
const TYPENAME_AABB := "AABB"
const TYPENAME_BASIS := "Basis"
const TYPENAME_TRANSFORM := "Transform"
const TYPENAME_COLOR := "Color"
const TYPENAME_NODE_PATH := "NodePath"
const TYPENAME_RID := "RID"
const TYPENAME_OBJECT := "Object"
const TYPENAME_DICTIONARY := "Dictionary"
const TYPENAME_ARRAY := "Array"
const TYPENAME_RAW_ARRAY := "PoolByteArray"
const TYPENAME_INT_ARRAY := "PoolIntArray"
const TYPENAME_REAL_ARRAY := "PoolRealArray"
const TYPENAME_STRING_ARRAY := "PoolStringArray"
const TYPENAME_VECTOR2_ARRAY := "PoolVector2Array"
const TYPENAME_VECTOR3_ARRAY := "PoolVector3Array"
const TYPENAME_COLOR_ARRAY := "PoolColorArray"
const TYPENAME_MAX := "Max"


const _TYPENAME := {
	TYPE_NIL: TYPENAME_NIL,
	TYPE_BOOL: TYPENAME_BOOL,
	TYPE_INT: TYPENAME_INT,
	TYPE_REAL: TYPENAME_REAL,
	TYPE_STRING: TYPENAME_STRING,
	TYPE_VECTOR2: TYPENAME_VECTOR2,
	TYPE_RECT2: TYPENAME_RECT2,
	TYPE_VECTOR3: TYPENAME_VECTOR3,
	TYPE_TRANSFORM2D: TYPENAME_TRANSFORM2D,
	TYPE_PLANE: TYPENAME_PLANE,
	TYPE_QUAT: TYPENAME_QUAT,
	TYPE_AABB: TYPENAME_AABB,
	TYPE_BASIS: TYPENAME_BASIS,
	TYPE_TRANSFORM: TYPENAME_TRANSFORM,
	TYPE_COLOR: TYPENAME_COLOR,
	TYPE_NODE_PATH: TYPENAME_NODE_PATH,
	TYPE_RID: TYPENAME_RID,
	TYPE_OBJECT: TYPENAME_OBJECT,
	TYPE_DICTIONARY: TYPENAME_DICTIONARY,
	TYPE_ARRAY: TYPENAME_ARRAY,
	TYPE_RAW_ARRAY: TYPENAME_RAW_ARRAY,
	TYPE_INT_ARRAY: TYPENAME_INT_ARRAY,
	TYPE_REAL_ARRAY: TYPENAME_REAL_ARRAY,
	TYPE_STRING_ARRAY: TYPENAME_STRING_ARRAY,
	TYPE_VECTOR2_ARRAY: TYPENAME_VECTOR2_ARRAY,
	TYPE_VECTOR3_ARRAY: TYPENAME_VECTOR3_ARRAY,
	TYPE_COLOR_ARRAY: TYPENAME_COLOR_ARRAY,
	TYPE_MAX: TYPENAME_MAX,
}


static func typename(type: int) -> String:
	return _TYPENAME[type]
